#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.

# Get the base directory dynamically
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "Setting environment variables..."

export CPILINT_HOME="$BASE_DIR"

# Check JAVA_HOME and log warnings if necessary
if [ -z "$JAVA_HOME" ] || [[ ! "$JAVA_HOME" == *"17"* ]]; then
    echo "Warning: JAVA_HOME is not set or does not contain '17': $JAVA_HOME"
else
    echo "Java 17 found at $JAVA_HOME"
    export CPILINT_JAVA_HOME="$JAVA_HOME"
fi

LAUNCH_SCRIPT="$CPILINT_HOME/scripts/cpilint"

echo "Copying runtime jars... $LAUNCH_SCRIPT"
mkdir -p "$CPILINT_HOME/lib"
cp "$BASE_DIR/build/lib/cpilint-1.0.5.jar" "$CPILINT_HOME/lib/"
cp "$BASE_DIR/lib/runtime/"*.jar "$CPILINT_HOME/lib/"
cp "$BASE_DIR/dist-files/xerces-runtime-jars/"*.jar "$CPILINT_HOME/lib/"

echo ""
echo "------ Example Commands ------"
echo ""
echo "./scripts/cpilint -help"
echo "./scripts/cpilint -debug -output json -rules rulesets/default.xml -key .env.json"
echo "./scripts/cpilint -debug -boring -output json -rules rulesets/default.xml -key .env.json -packages SPJPMTests"
echo "./scripts/cpilint -rules rulesets/default.xml -key .env.json -output json"
echo "./scripts/cpilint -help"
echo "./scripts/cpilint -skipvercheck -debug -output json -rules rulesets/jnj-base.xml -key .env.json"
echo "./scripts/cpilint -skipvercheck -debug -boring -output json -rules rulesets/jnj-base.xml -key .env.json -packages SPJPMTests"
echo "./scripts/cpilint -skipvercheck -rules rulesets/jnj-base.xml -key .env.json -output json"
echo "./scripts/cpilint -skipvercheck -debug -boring -output json -rules rulesets/jnj-base.xml -key .env.json -iflows IF_LINT -packages SP_JPM_Tests"
echo "./scripts/cpilint -debug -output json -rules rulesets/jnj-base.xml -unpacked-files resources/iflow-example-unzipped"
echo "./scripts/cpilint -debug -output json -rules rulesets/jnj-base.xml -unpacked-files resources/iflow-example-unzipped"
echo "Lint the whole dang tenant. 431 issues last time running it"
echo "./scripts/cpilint -debug -output json -rules rulesets/jnj-base.xml -key .env.json -skip-sap-packages -skip-drafts"
echo "./scripts/cpilint -debug -output json -rules rulesets/jnj-base.xml -key .env.json -packages SPJPMTests"
echo "./scripts/cpilint -debug -output json -rules rulesets/jnj-base.xml -directory resources/IntegrationContent"

echo To lint a directory of unzipped iflows which each exist in their own subdir, specify each dir after the -unpacked-files flag:
echo "./scripts/cpilint -debug -output json -rules rulesets/jnj-base.xml -unpacked-files ../sp_jpm_tests/IntegrationContent/IF_Common_ExampleHappyPath/ ./sp_jpm_tests/IntegrationContent/IF_LINT/"
